server:
  port: 9044
spring:
  datasource:
    url: jdbc:postgresql://osushi-nigiri-db.postgres.database.azure.com:5432/postgres
    username: adam@osushi-nigiri-db
    password: zaq12wsx!@
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    # hibernate:
    #   ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    xyz.ashiras: DEBUG
  file: logs/file.log